### ISSUE TITLE
Error with webpack - images

### ISSUE THREAD

**Issue by kolyaio** [amberframework/amber#919]
### Description

I put an image in the path `/src/assets/images/`
I'm using SCSS file to show the image in the background.
like that:
```
.blog-layout-transparent {
    background: url('/src/assets/images/transparent.jpg') center / cover;
}
```

But in the final code it should import the file from `/dist/assets/images' instead. 

But when I run the build it gives me the following error:
```
ERROR in ./src/assets/stylesheets/main.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './images/transparent.jpg' in '/Users/niko/code/blog/src/assets/stylesheets'
    at factoryCallback (/Users/niko/code/blog/node_modules/webpack/lib/Compilation.js:282:40)
    at factory (/Users/niko/code/blog/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
    at resolver (/Users/niko/code/blog/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/niko/code/blog/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /Users/niko/code/blog/node_modules/async/dist/async.js:3888:9
    at /Users/niko/code/blog/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/niko/code/blog/node_modules/async/dist/async.js:1062:13)
    at /Users/niko/code/blog/node_modules/async/dist/async.js:969:16
    at /Users/niko/code/blog/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/Users/niko/code/blog/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/niko/code/blog/node_modules/tapable/lib/Tapable.js:252:11)
    at /Users/niko/code/blog/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/niko/code/blog/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/niko/code/blog/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/Resolver.js:168:10)
    at loggingCallbackWrapper (/Users/niko/code/blog/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/niko/code/blog/node_modules/tapable/lib/Tapable.js:252:11)
 @ ./src/assets/stylesheets/main.scss

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/main.scss
Module not found: Error: Can't resolve './images/transparent.jpg' in '/Users/niko/code/blog/src/assets/stylesheets'
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/main.scss 7:83-118
 @ ./src/assets/stylesheets/main.scss
```

As I understand the Webpack default config should transfer the assets from the src folder into the dist folder but it returns the error above instead.  

**Reproduces how often:**  100%

### Versions
Amber CLI (amberframework.org) - v0.8.0

**Crystal Version:**

Crystal 0.25.1 (2018-06-30)
LLVM: 5.0.2
Default target: x86_64-apple-macosx

**OS:** 
   System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0

**webpack version**: ^3.12.0

**Comment by faustinoaq** [comment]
> Try Can't resolve `'./images/transparent.jpg'` in `'/Users/niko/code/blog/src/assets/stylesheets'`

Hi @kolyaio try:

```
.blog-layout-transparent {
    background: url('../images/transparent.jpg') center / cover;
}
```

**Comment by kolyaio** [comment]
Well that's really weird I tried it but it didn't work for me for some weird reason 👍  😕 😮
