### ISSUE TITLE
npm ERR! missing script: watch

### ISSUE THREAD

**Issue by Rojo** [amberframework/amber#956]
### Description

Toying with the _Quick Start_ instructions I was bitten by this NPM error while trying to run `amber watch`.

Per harps it is only a Webpack configuration missing... ?

Anyway, it seems to prevent the project from being served.

### Steps to Reproduce

Follow the _Quick Start_ tutorial and try to serve the project with `amber watch`

### Versions

- Crystal 0.26.1
- Amber 0.9.0
- Node.js 10.11.0
- NPM 6.4.1
- Ubuntu Bionic 18.04

### Additional Information

Console log:

```
vagrant@ubuntu-bionic:/vagrant$ amber watch
03:18:20 Watcher    | (INFO) Watching 252 files (server reload)...
03:18:20 Watcher    | (INFO) Building project Amber...
03:18:25 Watcher    | (INFO) Terminating app Amber...
03:18:25 Watcher    | (INFO) Starting Amber...
03:18:25 NodeJS     | (INFO) Installing dependencies...
03:18:25 NodeJS     | (INFO) Watching public directory
audited 5034 packages in 13.469s
found 0 vulnerabilities

npm ERR! missing script: watch

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-09-27T03_18_40_276Z-debug.log
```

2018-09-27T03_18_40_276Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v10.11.0/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v10.11.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose stack Error: missing script: watch
4 verbose stack     at run (/home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /home/vagrant/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /vagrant
6 verbose Linux 4.15.0-34-generic
7 verbose argv "/home/vagrant/.nvm/versions/node/v10.11.0/bin/node" "/home/vagrant/.nvm/versions/node/v10.11.0/bin/npm" "run" "watch"
8 verbose node v10.11.0
9 verbose npm  v6.4.1
10 error missing script: watch
11 verbose exit [ 1, true ]
```

**Comment by Rojo** [comment]
This repo may be useful to replicate: https://bitbucket.org/akaiiro_projects/concept-amber-framework-quick-start/src/master/

**Comment by Rojo** [comment]
@elorest Seems that my project was polluted with files from a previous version and it caused the conflict.
